---
title: Dr Lewis Plastic Surgery
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  procedures:
    title: Procedures
    output: true
  uploads:
    title: Uploads
    output: true
email: info@drlewisplasticsurgery.com
description: Plastic surgery is first a medical science, but it also a fine art. Few
  surgeons embody the best of both disciplines more aptly than Dr. Robert Lewis. Dr.
  Lewis has the credentials and clinical experience that informed patients want in
  a surgeon. He also has the artistic skills – the eye, deft touch and appreciation
  for nuance – that create the difference between good and optimal results. And by
  the way, Dr. Lewis believes in active listening – in order to better understand
  his patients concerns and preferences.
baseurl: ''
url: ''
theme: minima
plugins:
- jekyll-feed
